export interface MetaData {
  title: string;
  keywords: string;
  description: string;
  og_image: string;
  og_type: string;
  canonical: string;
  schema?: {
    "@context": string;
    "@type": string;
    name: string;
    description: string;
    url: string;
  };
  og_url?: string;
}

export const META_CONFIG: Record<string, MetaData> = {
  home: {
    title: "Pallapay - Cryptocurrency Payment Solutions",
    keywords: "crypto payments, bitcoin, ethereum, USDT",
    description: "Pallapay is your gateway to seamless cryptocurrency payments",
    og_image: "/images/home-og.jpg",
    og_type: "website",
    canonical: "/",
    schema: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Pallapay",
      description:
        "Pallapay is your gateway to seamless cryptocurrency payments",
      url: "/",
    },
  },
  faq: {
    title: "FAQ - Pallapay",
    keywords: "frequently asked questions, help, support",
    description: "Get answers to common questions about Pallapay",
    og_image: "/images/faq-og.jpg",
    og_type: "website",
    canonical: "/faq",
    schema: {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      name: "FAQ",
      description: "Get answers to common questions about Pallapay",
      url: "/faq",
    },
  },
  wallet: {
    title: "Wallet - Pallapay",
    keywords: "crypto wallet, ethereum, bitcoin",
    description: "Secure cryptocurrency wallet solutions",
    og_image: "/images/wallet-og.jpg",
    og_type: "website",
    canonical: "/wallet",
    schema: {
      "@context": "https://schema.org",
      "@type": "ProductPage",
      name: "Wallet",
      description: "Secure cryptocurrency wallet solutions",
      url: "/wallet",
    },
  },
  pricing: {
    title: "Pricing - Pallapay",
    keywords: "pricing, rates, fees",
    description: "Check out our competitive pricing for crypto payments",
    og_image: "/images/pricing-og.jpg",
    og_type: "website",
    canonical: "/pricing",
    schema: {
      "@context": "https://schema.org",
      "@type": "PricingPage",
      name: "Pricing",
      description: "Check out our competitive pricing for crypto payments",
      url: "/pricing",
    },
  },
  about: {
    title: "About Us - Pallapay",
    keywords: "about, company, mission",
    description: "Learn about Pallapay and our mission",
    og_image: "/images/about-og.jpg",
    og_type: "website",
    canonical: "/about-us",
    schema: {
      "@context": "https://schema.org",
      "@type": "AboutPage",
      name: "About Us",
      description: "Learn about Pallapay and our mission",
      url: "/about-us",
    },
  },
  "official-wallet-addresses": {
    title: "Official Wallet Addresses - Pallapay",
    keywords: "wallet addresses, official",
    description: "Official wallet addresses for Pallapay",
    og_image: "/images/official-wallet-addresses-og.jpg",
    og_type: "website",
    canonical: "/official-wallet-addresses",
  },
  contact: {
    title: "Contact Us - Pallapay",
    keywords: "contact, support, help",
    description: "Get in touch with Pallapay",
    og_image: "/images/contact-og.jpg",
    og_type: "website",
    canonical: "/contact-us",
  },
  "industries.gaming": {
    title: "Gaming Solutions - Pallapay",
    keywords: "gaming, crypto payments, entertainment",
    description: "Cryptocurrency payment solutions for gaming industry",
    og_image: "/images/gaming-og.jpg",
    og_type: "website",
    canonical: "/industries/gaming",
  },
  "industries.casinos": {
    title: "Casino Payment Solutions - Pallapay",
    keywords: "casino, crypto payments",
    description: "Secure payment solutions for casinos",
    og_image: "/images/casinos-og.jpg",
    og_type: "website",
    canonical: "/industries/casinos",
  },
  "industries.hotels": {
    title: "Hotel Payment Solutions - Pallapay",
    keywords: "hotel, hospitality, payments",
    description: "Payment solutions for hotels and hospitality",
    og_image: "/images/hotels-og.jpg",
    og_type: "website",
    canonical: "/industries/hotels",
  },
  "industries.trading-platforms": {
    title: "Trading Platform Solutions - Pallapay",
    keywords: "trading, forex, crypto",
    description: "Payment solutions for trading platforms",
    og_image: "/images/trading-platforms-og.jpg",
    og_type: "website",
    canonical: "/industries/trading-platforms",
  },
  "industries.ecommerce": {
    title: "E-commerce Solutions - Pallapay",
    keywords: "ecommerce, online store, payments",
    description: "Payment solutions for e-commerce businesses",
    og_image: "/images/ecommerce-og.jpg",
    og_type: "website",
    canonical: "/industries/ecommerce",
  },
  "industries.retail-store": {
    title: "Retail Solutions - Pallapay",
    keywords: "retail, point of sale, payments",
    description: "Payment solutions for retail stores",
    og_image: "/images/retail-store-og.jpg",
    og_type: "website",
    canonical: "/industries/retail-store",
  },
  "industries.all": {
    title: "All Solutions - Pallapay",
    keywords: "solutions, industries",
    description: "All industry solutions by Pallapay",
    og_image: "/images/all-solutions-og.jpg",
    og_type: "website",
    canonical: "/industries/all",
  },
  "products.fiat-settlement": {
    title: "Fiat Settlement - Pallapay",
    keywords: "fiat settlement, conversion",
    description: "Instant fiat settlement for crypto payments",
    og_image: "/images/fiat-settlement-og.jpg",
    og_type: "website",
    canonical: "/products/fiat-settlement",
  },
  "products.payment-api": {
    title: "Payment API - Pallapay",
    keywords: "API, payment integration",
    description: "Payment API for crypto integration",
    og_image: "/images/payment-api-og.jpg",
    og_type: "website",
    canonical: "/products/payment-api",
  },
  "products.payment-link": {
    title: "Payment Link - Pallapay",
    keywords: "payment link, easy payment",
    description: "Create payment links easily",
    og_image: "/images/payment-link-og.jpg",
    og_type: "website",
    canonical: "/products/payment-link",
  },
  "products.pos-machine": {
    title: "Crypto POS Machine - Pallapay",
    keywords: "POS machine, point of sale",
    description: "Cryptocurrency point of sale machine",
    og_image: "/images/pos-machine-og.jpg",
    og_type: "website",
    canonical: "/crypto-pos-machine",
  },
  "products.gift-card": {
    title: "Gift Cards - Pallapay",
    keywords: "gift cards, digital gifts",
    description: "Send crypto gift cards",
    og_image: "/images/gift-card-og.jpg",
    og_type: "website",
    canonical: "/products/gift-card",
  },
  "buy-bitcoin-in-dubai": {
    title: "Buy Bitcoin in Dubai - Pallapay",
    keywords: "buy bitcoin, dubai, UAE",
    description: "Buy Bitcoin easily in Dubai",
    og_image: "/images/buy-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/buy-bitcoin-in-dubai",
  },
  "buy-bitcoin-dubai": {
    title: "Buy Bitcoin in Dubai - Pallapay",
    keywords: "buy bitcoin, dubai, prices",
    description: "Check Bitcoin prices and buy in Dubai",
    og_image: "/images/buy-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/buy-bitcoin-dubai",
  },
  "buy-bitcoin-turkey": {
    title: "Buy Bitcoin in Turkey - Pallapay",
    keywords:
      "buy bitcoin, turkey, TRY, cryptocurrency, Buy Bitcoin with cash in Istanbul, Turkey",
    description: "Buy Bitcoin easily in Turkey with Pallapay",
    og_image: "/images/buy-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/buy-bitcoin-turkey",
  },
  "buy-bitcoin-in-istanbul": {
    title: "Buy Bitcoin in Istanbul - Pallapay",
    keywords: "buy bitcoin, istanbul, turkey, TRY, cryptocurrency",
    description: "Buy Bitcoin easily in Istanbul with Pallapay",
    og_image: "/images/buy-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/buy-bitcoin-in-istanbul",
  },
  "buy-sell-bitcoin-tether-dubai": {
    title: "Buy/Sell Bitcoin & USDT in Dubai - Pallapay",
    keywords: "buy sell bitcoin, USDT, dubai",
    description: "Buy and sell Bitcoin and USDT in Dubai",
    og_image: "/images/buy-sell-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/buy-sell-bitcoin-tether-dubai",
  },
  "sell-usdt-in-dubai": {
    title: "Sell USDT in Dubai - Pallapay",
    keywords: "sell USDT, tether, dubai",
    description: "Sell USDT in Dubai easily",
    og_image: "/images/sell-usdt-og.jpg",
    og_type: "website",
    canonical: "/sell-usdt-in-dubai",
  },
  "sell-usdt-in-istanbul": {
    title: "Sell USDT in Istanbul - Pallapay",
    keywords: "sell USDT, tether, istanbul",
    description: "Sell USDT in Istanbul",
    og_image: "/images/sell-usdt-og.jpg",
    og_type: "website",
    canonical: "/sell-usdt-in-istanbul",
  },
  "sell-bnb-in-dubai": {
    title: "Sell BNB in Dubai - Pallapay",
    keywords: "sell BNB, binance, dubai",
    description: "Sell Binance Coin in Dubai",
    og_image: "/images/sell-bnb-og.jpg",
    og_type: "website",
    canonical: "/sell-bnb-in-dubai",
  },
  "sell-shiba-in-dubai": {
    title: "Sell SHIBA in Dubai - Pallapay",
    keywords: "sell SHIBA, shib, dubai",
    description: "Sell Shiba Inu token in Dubai",
    og_image: "/images/sell-shiba-og.jpg",
    og_type: "website",
    canonical: "/sell-shiba-in-dubai",
  },
  "sell-xrp-in-dubai": {
    title: "Sell XRP in Dubai - Pallapay",
    keywords: "sell XRP, ripple, dubai",
    description: "Sell XRP in Dubai",
    og_image: "/images/sell-xrp-og.jpg",
    og_type: "website",
    canonical: "/sell-xrp-in-dubai",
  },
  "sell-ethereum-in-dubai": {
    title: "Sell Ethereum in Dubai - Pallapay",
    keywords: "sell ethereum, ETH, dubai",
    description: "Sell Ethereum in Dubai",
    og_image: "/images/sell-ethereum-og.jpg",
    og_type: "website",
    canonical: "/sell-ethereum-in-dubai",
  },
  "sell-ethereum-in-istanbul": {
    title: "Sell Ethereum in Istanbul - Pallapay",
    keywords: "sell ethereum, ETH, istanbul",
    description: "Sell Ethereum in Istanbul",
    og_image: "/images/sell-ethereum-og.jpg",
    og_type: "website",
    canonical: "/sell-ethereum-in-istanbul",
  },
  "sell-bitcoin-in-dubai": {
    title: "Sell Bitcoin in Dubai - Pallapay",
    keywords: "sell bitcoin, BTC, dubai",
    description: "Sell Bitcoin in Dubai",
    og_image: "/images/sell-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/sell-bitcoin-in-dubai",
  },
  "sell-bitcoin-in-istanbul": {
    title: "Sell Bitcoin in Istanbul - Pallapay",
    keywords: "sell bitcoin, BTC, istanbul",
    description: "Sell Bitcoin in Istanbul",
    og_image: "/images/sell-bitcoin-og.jpg",
    og_type: "website",
    canonical: "/sell-bitcoin-in-istanbul",
  },
  "buy-usdt-in-dubai": {
    title: "Buy USDT in Dubai - Pallapay",
    keywords: "buy USDT, tether, dubai",
    description: "Buy USDT in Dubai",
    og_image: "/images/buy-usdt-og.jpg",
    og_type: "website",
    canonical: "/buy-usdt-in-dubai",
  },
  "buy-ethereum-in-dubai": {
    title: "Buy Ethereum in Dubai - Pallapay",
    keywords: "buy ethereum, ETH, dubai",
    description: "Buy Ethereum in Dubai",
    og_image: "/images/buy-ethereum-og.jpg",
    og_type: "website",
    canonical: "/buy-ethereum-in-dubai",
  },
  "buy-usdt-in-istanbul": {
    title: "Buy USDT in Istanbul - Pallapay",
    keywords: "buy USDT, tether, istanbul, turkey",
    description: "Buy USDT in Istanbul",
    og_image: "/images/buy-usdt-og.jpg",
    og_type: "website",
    canonical: "/buy-usdt-in-istanbul",
  },
  "buy-ethereum-in-istanbul": {
    title: "Buy Ethereum in Istanbul - Pallapay",
    keywords: "buy ethereum, ETH, istanbul, turkey",
    description: "Buy Ethereum in Istanbul",
    og_image: "/images/buy-ethereum-og.jpg",
    og_type: "website",
    canonical: "/buy-ethereum-in-istanbul",
  },
  agreement: {
    title: "Terms of Service - Pallapay",
    keywords: "terms, agreement, legal",
    description: "Terms of service for Pallapay",
    og_image: "/images/agreement-og.jpg",
    og_type: "website",
    canonical: "/agreement",
  },
  "prohibited-use": {
    title: "Prohibited Use - Pallapay",
    keywords: "prohibited, terms",
    description: "Prohibited use policy",
    og_image: "/images/prohibited-use-og.jpg",
    og_type: "website",
    canonical: "/prohibited-use",
  },
  "prohibited-countries": {
    title: "Prohibited Countries - Pallapay",
    keywords: "prohibited countries",
    description: "List of prohibited countries",
    og_image: "/images/prohibited-countries-og.jpg",
    og_type: "website",
    canonical: "/prohibited-countries",
  },
  "gift-card-terms": {
    title: "Gift Card Terms - Pallapay",
    keywords: "gift card, terms",
    description: "Gift card terms and conditions",
    og_image: "/images/gift-card-terms-og.jpg",
    og_type: "website",
    canonical: "/gift-card-terms",
  },
  "general-risk-warning": {
    title: "Risk Warning - Pallapay",
    keywords: "risk, warning, disclaimer",
    description: "General risk warning",
    og_image: "/images/risk-warning-og.jpg",
    og_type: "website",
    canonical: "/general-risk-warning",
  },
  privacy: {
    title: "Privacy Policy - Pallapay",
    keywords: "privacy, policy, data protection",
    description: "Privacy policy for Pallapay",
    og_image: "/images/privacy-og.jpg",
    og_type: "website",
    canonical: "/privacy",
  },
  "kyc-policy": {
    title: "KYC Policy - Pallapay",
    keywords: "KYC, know your customer",
    description: "KYC policy and procedures",
    og_image: "/images/kyc-policy-og.jpg",
    og_type: "website",
    canonical: "/kyc-policy",
  },
  "gift-card-intro": {
    title: "Gift Cards - Pallapay",
    keywords: "gift cards, crypto gifts",
    description: "Send crypto gifts with Pallapay",
    og_image: "/images/gift-card-intro-og.jpg",
    og_type: "website",
    canonical: "/gift-card-intro",
  },
};

export function getMetaData(key: string): MetaData {
  return META_CONFIG[key] || META_CONFIG.home;
}
